var l=function(e){var c=0;return function(){return c<e.length?{done:!1,value:e[c++]}:{done:!0}}},m=function(e){var c="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return c?c.call(e):{next:l(e)}},n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,p="function"==typeof Object.defineProperties?Object.defineProperty:function(e,c,g){e!=Array.prototype&&e!=Object.prototype&&(e[c]=g.value)},r=function(e){if(e){for(var c=n,g=["Promise"],
f=0;f<g.length-1;f++){var b=g[f];b in c||(c[b]={});c=c[b]}g=g[g.length-1];f=c[g];e=e(f);e!=f&&null!=e&&p(c,g,{configurable:!0,writable:!0,value:e})}};
r(function(e){function c(){this.a=null}function g(a){return a instanceof b?a:new b(function(d){d(a)})}if(e)return e;c.prototype.b=function(a){null==this.a&&(this.a=[],this.f());this.a.push(a)};c.prototype.f=function(){var a=this;this.c(function(){a.i()})};var f=n.setTimeout;c.prototype.c=function(a){f(a,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var d=0;d<a.length;++d){var b=a[d];a[d]=null;try{b()}catch(k){this.g(k)}}}this.a=null};c.prototype.g=function(a){this.c(function(){throw a;
})};var b=function(a){this.b=0;this.g=void 0;this.a=[];var d=this.c();try{a(d.resolve,d.reject)}catch(h){d.reject(h)}};b.prototype.c=function(){function a(a){return function(c){b||(b=!0,a.call(d,c))}}var d=this,b=!1;return{resolve:a(this.o),reject:a(this.f)}};b.prototype.o=function(a){if(a===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.s(a);else{a:switch(typeof a){case "object":var d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.m(a):
this.i(a)}};b.prototype.m=function(a){var d=void 0;try{d=a.then}catch(h){this.f(h);return}"function"==typeof d?this.u(d,a):this.i(a)};b.prototype.f=function(a){this.j(2,a)};b.prototype.i=function(a){this.j(1,a)};b.prototype.j=function(a,d){if(0!=this.b)throw Error("Cannot settle("+a+", "+d+"): Promise already settled in state"+this.b);this.b=a;this.g=d;this.l()};b.prototype.l=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)q.b(this.a[a]);this.a=null}};var q=new c;b.prototype.s=function(a){var d=
this.c();a.h(d.resolve,d.reject)};b.prototype.u=function(a,d){var b=this.c();try{a.call(d,b.resolve,b.reject)}catch(k){b.reject(k)}};b.prototype.then=function(a,d){function c(a,d){return"function"==typeof a?function(d){try{e(a(d))}catch(w){g(w)}}:d}var e,g,f=new b(function(a,d){e=a;g=d});this.h(c(a,e),c(d,g));return f};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.h=function(a,d){function b(){switch(c.b){case 1:a(c.g);break;case 2:d(c.g);break;default:throw Error("Unexpected state: "+
c.b);}}var c=this;null==this.a?q.b(b):this.a.push(b)};b.resolve=g;b.reject=function(a){return new b(function(d,b){b(a)})};b.race=function(a){return new b(function(d,b){for(var c=m(a),e=c.next();!e.done;e=c.next())g(e.value).h(d,b)})};b.all=function(a){var d=m(a),c=d.next();return c.done?g([]):new b(function(a,b){function e(b){return function(c){f[b]=c;h--;0==h&&a(f)}}var f=[],h=0;do f.push(void 0),h++,g(c.value).h(e(f.length-1),b),c=d.next();while(!c.done)})};return b});
function t(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");u()}var u,v=null;
function x(){if(v)return v;window.performance.mark("gapi_load_start");var e=window.colabExperiments&&window.colabExperiments.first_party_auth;return v=new Promise(function(c,g){u=c;window.gapi_onload=function(){e?u():gapi.load("auth:client",t)};var f=document.createElement("script");f.src="https://apis.google.com/js/client.js";f.async=!0;f.onerror=function(){g(Error("Error loading "+f.src))};c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(f,c)})}window.colab_gapi_loader={};
window.colab_gapi_loader.load=x;x().then(function(){},function(){});
